# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "shub's list o' links"

# Avatar image path
avatar: "./images/shub-logo.png"

# Name section text
name: "shub"

# Tagline section text
tagline: >-
    A gaming content creator philanthropist.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-medium"
      text: "Twitch"
      url: "https://twitch.tv/megashub"
      alt: "Twitch"
      title: "Twitch"
      target: "_blank"
  - link:
      icon: "fa-brands fa-medium"
      text: "Contact Form"
      url: "https://megashub.github.io/contact"
      alt: "Contact Form"
      title: "Contact Form"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
# socials:
#   - social:
#       icon: "fa-brands fa-medium"
#       url: "https://blog.zhgchg.li"
#       title: "ZhgChgLi's Medium"
#       alt: "ZhgChgLi's Medium"
#       target: "_blank"
#   - social:
#       icon: "fa-brands fa-github"
#       url: "https://github.com/ZhgChgLi"
#       title: "ZhgChgLi's GitHub"
#       alt: "ZhgChgLi's GitHub"
#       target: "_blank"
#   - social:
#       icon: "fa-brands fa-twitter"
#       url: "https://twitter.com/zhgchgli"
#       title: "ZhgChgLi's Twitter"
#       alt: "ZhgChgLi's Twitter"
#       target: "_blank"
#   - social:
#       icon: "fa-brands fa-linkedin"
#       url: "https://www.linkedin.com/in/zhgchgli/"
#       title: "ZhgChgLi's LinkedIn"
#       alt: "ZhgChgLi's LinkedIn"
#       target: "_blank"
#   - social:
#       icon: "fa-brands fa-instagram"
#       url: "https://www.instagram.com/zhgchgli/"
#       title: "Instagram"
#       alt: "ZhgChgLi's Instagram"
#       target: "_blank"
#   - social:
#     icon: "fa-solid fa-envelope"
#       url: "mailto:zhgchgli@gmail.com"
#       title: "Email: zhgchgli@gmail.com"
#       alt: "zhgchgli@gmail.com"
#       target: "_blank"

# Footer text
footer: >
    I stream every Sunday on Twitch, usually at 1pm US PT.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025 shub. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
